// src/app/task.service.ts
// This service handles all HTTP communication with your Spring Boot backend's Task API.

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http'; // Required for making HTTP requests
import { Observable } from 'rxjs'; // For handling asynchronous operations

// Define the structure of a Task object, matching the backend's Task model
export interface Task { // Make sure 'Task' interface is exported if used in other files
  id?: number;           // Optional, as it's generated by the backend
  title: string;
  description: string;
  dueDate: string;       // Using string for simplicity, can be Date
  completed: boolean;
  tags?: string[];       // Array of strings for tags
}

@Injectable({
  providedIn: 'root' // Makes this service a singleton and available throughout the app
})
export class TaskService {
  // The base URL for your Spring Boot backend's Task API
  private apiUrl = 'http://localhost:8080/api/tasks';

  // Define HTTP options, specifically for content type when sending JSON
  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Inject the HttpClient service into our TaskService
  constructor(private http: HttpClient) { }

  /**
   * Fetches all tasks from the backend.
   * @returns An Observable of an array of Task objects.
   */
  getTasks(): Observable<Task[]> {
    return this.http.get<Task[]>(this.apiUrl);
  }

  /**
   * Sends a new task to the backend to be created.
   * @param task The Task object to add.
   * @returns An Observable of the created Task object (with its ID from the backend).
   */
  addTask(task: Task): Observable<Task> {
    return this.http.post<Task>(this.apiUrl, task, this.httpOptions); // Use httpOptions for POST
  }

  /**
   * Updates an existing task on the backend.
   * @param task The Task object with updated information.
   * @returns An Observable of the updated Task object.
   */
  updateTask(task: Task): Observable<Task> {
    // ⭐⭐⭐ CORRECTED: Using backticks (`) for template literals to build the URL ⭐⭐⭐
    const url = `${this.apiUrl}/${task.id}`;
    return this.http.put<Task>(url, task, this.httpOptions); // Use httpOptions for PUT
  }

  /**
   * Toggles the completion status of a task.
   * This method first flips the 'completed' status of the task object
   * and then sends the entire updated task object to the backend via updateTask.
   * @param task The Task object whose completion status needs to be toggled.
   * @returns An Observable of the updated Task object.
   */
  toggleTaskCompletion(task: Task): Observable<Task> {
    // Create a new object with the toggled 'completed' status
    const updatedTask = { ...task, completed: !task.completed };
    // Call the general updateTask method to send the full updated object to the backend
    return this.updateTask(updatedTask);
  }

  /**
   * Deletes a task from the backend.
   * @param id The ID of the task to delete.
   * @returns An Observable of type void (no content expected back on successful deletion).
   */
  deleteTask(id: number): Observable<void> {
    // ⭐⭐⭐ CORRECTED: Using backticks (`) for template literals to build the URL ⭐⭐⭐
    const url = `${this.apiUrl}/${id}`;
    return this.http.delete<void>(url);
  }
}